source:          .
destination:     ./_site
collections_dir: ./docs
plugins_dir:     ./docs/_plugins
layouts_dir:     ./docs/_layouts
data_dir:        ./docs/_data
includes_dir:    ./docs/_includes
collections:
  assets:
    output:             true
    permalink:          :collection/:path/
  en:
    output:             true
    permalink:          :path/
    relative_directory: _pages
  id:
    output:             true
    permalink:          /:collection/:path/
    relative_directory: _pages

# Serving
port: 4000
host: 127.0.0.1
url:  "https://technoartcss.com"

# Handling Reading
exclude:
  - .git/
  - .github/
  - build/
  - dist-components/
  - node_modules/
  - nuget/
  - src/
  - test/
  - vendor/
  - CODE_OF_CONDUCT.md
  - composer.json
  - Gemfile
  - Gemfile.lock
  - package.js
  - package.json
  - package-lock.json
  - sache.json
  - technoprodevconfig.yml

# Plugins
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap

# Outputting
permalink: pretty

# Custom variables
title:       Technoart
description: No more custom CSS - All in one CSS framework for developing clean, professional & responsive web app.
authors:     Fandy Pradana
keywords:    css, sass, js, all-in-one, framework, clean, professional, responsive, web, app, simple, reliable, no-dependencies
version:     0.0.9

languages:
  en: English
  id: Indonesia

repo:      https://github.com/technoprodev/technoart
instagram: https://instagram.com/technoart
twitter:   https://twitter.com/technoart

download:
  source: https://github.com/technoprodev/technoart/archive/v0.0.9.zip
  dist:   https://github.com/technoprodev/technoart/releases/download/v0.0.9/bootstrap-0.9.9-dist.zip

cdn:
  css:      https://cdn.jsdelivr.net/npm/technoart@0.0.9/dist/css/technoart.min.css
  js:       https://cdn.jsdelivr.net/npm/technoart@0.0.9/dist/js/technoart.min.js
